---
- name: Configure Deployment Hosts
  ansible.builtin.import_playbook: infrastructure/playbooks/deployment.yaml

- name: Configure Switche
  ansible.builtin.import_playbook: infrastructure/playbooks/switche.yaml

- name: Configure Hypervisor Hosts
  ansible.builtin.import_playbook: infrastructure/playbooks/hypervisor.yaml

- name: Configure Virtual Machines
  ansible.builtin.import_playbook: infrastructure/playbooks/virtual-machine.yaml

