---
- hosts: switch
  gather_facts: false
  become: false

  pre_tasks:
  - ansible.builtin.debug:
      msg: Configure Switche
    delegate_to: localhost

  roles:
  - role: sodola
    when: platform == "soos"

  - role: tplink
    when: platform == "tpos"
